#CRIANDO O BANCO DE DADOS
CREATE DATABASE IF NOT EXISTS PASSAGENS_AEREAS;
USE PASSAGENS_AEREAS;

#CRIANDO A TABELA ENDERECOS
CREATE TABLE IF NOT EXISTS ENDERECOS(
    END_ID INT PRIMARY KEY AUTO_INCREMENT,
    END_RUA VARCHAR(45) NOT NULL,
    END_NUMRUA INT NOT NULL,
    END_BAIRRO VARCHAR(45) NOT NULL,
    END_CIDADE VARCHAR(45) NOT NULL,
    END_ESTADO VARCHAR(45) NOT NULL,
    END_CEP VARCHAR(20) NOT NULL,
    END_PAIS VARCHAR(30) NOT NULL
);

#CRIANDO A TABELA PASSAGEIROS
CREATE TABLE IF NOT EXISTS PASSAGEIROS(
     PASS_CPF VARCHAR(45) PRIMARY KEY,
    PASS_NOME VARCHAR(45) NOT NULL,
    PASS_TELEFONE VARCHAR(15),
    PASS_RUA VARCHAR(45),
    PASS_NUMRUA INT,
    PASS_BAIRRO VARCHAR(45) NOT NULL,
    PASS_CIDADE VARCHAR(45) NOT NULL,
    PASS_ESTADO VARCHAR(45) NOT NULL,
    PASS_PAIS VARCHAR(30) NOT NULL,
    PASS_CODPOSTAL VARCHAR(10) NOT NULL,
    PASS_CONTATO TEXT NOT NULL,
    PASS_EMAIL VARCHAR(11) NOT NULL
    FOREIGN KEY (END_ID) REFERENCES ENDERECOS(END_ID)
);

#CRIANDO A TABELA FUNCIONARIOS
CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
    FUNC_ID INT PRIMARY KEY AUTO_INCREMENT,
    FUNC_NOME VARCHAR(45) NOT NULL,
    FUNC_CPF VARCHAR(11) NOT NULL,
    FUNC_DATANASC DATE NOT NULL,
    FUNC_SALARIO DECIMAL(10,2),
    END_ID INT,
    FOREIGN KEY (END_ID) REFERENCES ENDERECOS(END_ID)
);

#CRIANDO A TABELA AEROPORTOS
CREATE TABLE IF NOT EXISTS AEROPORTOS(
    AEROP_COD INT PRIMARY KEY,
    NOME_AEROPORTO VARCHAR(30) NOT NULL,
    AEROP_RUA VARCHAR(45) NOT NULL,
    AEROP_NUMRUA INT NOT NULL,
    AEROP_BAIRRO VARCHAR(45) NOT NULL,
    AEROP_CIDADE VARCHAR(45) NOT NULL,
    AEROP_ESTADO VARCHAR(45) NOT NULL,
    AEROP_CEP VARCHAR(20) NOT NULL,
    AEROP_PAIS VARCHAR(30) NOT NULL,
    AEROP_LATITUDE DECIMAL(10,8) NOT NULL,
    AEROP_LONGITUDE DECIMAL(11,8) NOT NULL,
    AEROP_WEBSITE VARCHAR(100)
);

#CRIANDO A TABELA AERONAVES
CREATE TABLE IF NOT EXISTS AERONAVES(
    PREFIXO_AERONAVE INT PRIMARY KEY,
    AERON_MODELO VARCHAR(30) NOT NULL,
    AERON_MATRICULA VARCHAR(20),
    AERON_AUTONOMIA INT,
    AERON_CAPACIDADE INT,
    AERON_FABRICANTE VARCHAR(45)
);

#CRIANDO A TABELA VOOS
CREATE TABLE IF NOT EXISTS VOOS(
    CODIGO_VOO INT PRIMARY KEY AUTO_INCREMENT,
    VOO_DATA DATETIME NOT NULL,
    AEROP_ORIGEM_COD INT,
    AEROP_DESTINO_COD INT,
    PREFIXO_AERONAVE INT,
    FOREIGN KEY (AEROP_ORIGEM_COD) REFERENCES AEROPORTOS(AEROP_COD),
    FOREIGN KEY (AEROP_DESTINO_COD) REFERENCES AEROPORTOS(AEROP_COD),
    FOREIGN KEY (PREFIXO_AERONAVE) REFERENCES AERONAVES(PREFIXO_AERONAVE)
);

#CRIANDO A TABELA RESERVAS
CREATE TABLE IF NOT EXISTS RESERVAS(
    RESERVA_COD VARCHAR(10) PRIMARY KEY,
    CPF_PASSAGEIRO_RESERVA VARCHAR(11) NOT NULL,
    CODIGO_VOO INT NOT NULL,
    RESERVA_DATA DATE NOT NULL,
    FOREIGN KEY (CPF_PASSAGEIRO_RESERVA) REFERENCES PASSAGEIROS(PASS_CPF),
    FOREIGN KEY (CODIGO_VOO) REFERENCES VOOS(CODIGO_VOO)
);

ALTER TABLE AEROPORTOS
MODIFY COLUMN CPF_PASSAGEIRO_RESERVA VARCHAR(34) NOT NULL,
MODIFY COLUMN VOO_DATA DATA NOT NULL,
ADD COLUMN AEROP_DATA DATETIME,
CHANGE COLUMN AEROP_NOME NOME_AEROPORTO VARCHAR(30) NOT NULL;

ALTER TABLE AERONAVES
ADD COLUMN AERON_MATRICULA VARCHAR(20),
DROP COLUMN AERON_ANOFABR,
MODIFY COLUMN AERON_AUTONOMIA INT,
MODIFY COLUMN AERON_CAPACIDADE INT,
CHANGE COLUMN AERON_PREFIXO PREFIXO_AERONAVE INT PRIMARY KEY;

ALTER TABLE PASSAGEIROS
ADD COLUMN PASS_DATANASCIMENTO DATE,
DROP COLUMN PASS_TELEFONE,
MODIFY COLUMN PASS_CPF VARCHAR(11) PRIMARY KEY,
CHANGE COLUMN PASS_NOME NOME_PASSAGEIRO VARCHAR(30) NOT NULL;

ALTER TABLE RESERVAS
ADD COLUMN RESERVA_DATA DATE NOT NULL,
DROP COLUMN RESERVA_VOO_ID,
MODIFY COLUMN RESERVA_COD VARCHAR(10) PRIMARY KEY,
CHANGE COLUMN RESERVA_PASS_CPF CPF_PASSAGEIRO_RESERVA INT NOT NULL;

ALTER TABLE VOOS
ADD COLUMN VOO_STATUS VARCHAR(20),
DROP COLUMN VOO_HORA,
MODIFY COLUMN VOO_DATA DATETIME NOT NULL,
CHANGE COLUMN VOO_ID CODIGO_VOO INT PRIMARY KEY;

ALTER TABLE FUNCIONARIOS
ADD COLUMN FUNCK_SALARIO DECIMAL(10,2),
DROP COLUMN FUNCK_CEP,
MODIFY COLUMN FUNCK_CPF VARCHAR(22) NOT NULL,
CHANGE COLUMN FUNCK_NOME NOME_FUNCIONARIO VARCHAR(45) NOT NULL;

DROP DATABASE PASSAGENS_AEREAS;