CREATE DATABASE ERP_EMPRESARIAL;
USE ERP_EMPRESARIAL;

CREATE TABLE IF NOT EXISTS TIPO_ENDERECO (
    ID_TIPO_ENDERECO INT PRIMARY KEY,
    DESCRICAO VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS ENDERECOS (
    ID_ENDERECO INT PRIMARY KEY,
    RUA VARCHAR(100) NOT NULL,
    NUMERO INT,
    LOGRADOURO VARCHAR(100) NOT NULL,
    BAIRRO VARCHAR(100) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,
    ESTADO VARCHAR(100) NOT NULL,
    CEP CHAR(8) NOT NULL,
    PAIS VARCHAR(30) NOT NULL,
    ID_TIPO_DE_ENDERECO INT,
    OBSERVACOES TEXT,
    CONSTRAINT FK_ID_TIPO_DE_ENDERECO FOREIGN KEY (ID_TIPO_DE_ENDERECO) REFERENCES TIPO_DE_ENDERECO(ID_TIPO_DE_ENDERECO)
);

CREATE TABLE IF NOT EXISTS PESSOAS (
    ID_PESSOA INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) UNIQUE,
    EMAIL VARCHAR(100),
    ID_ENDERECO INT,
    CONSTRAINT FK_ID_ENDERECO FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECOS(ID_ENDERECO)
);

CREATE TABLE IF NOT EXISTS CLIENTES (
    ID_CLIENTE INT PRIMARY KEY,
    CNPJ VARCHAR(14) UNIQUE,
    DATA_CADASTRO DATE NOT NULL,
    RAZAO_SOCIAL VARCHAR(200) NOT NULL,
    ID_PESSOA INT,
    CONSTRAINT FK_ID_PESSOA_CLIENTE FOREIGN KEY (ID_PESSOA) REFERENCES PESSOAS(ID_PESSOA)
);

CREATE TABLE IF NOT EXISTS EMPREGADOS (
    ID_EMPREGADO INT PRIMARY KEY,
    DATA_ADMISSAO DATETIME NOT NULL,
    ID_CARGO INT,
    ID_PESSOA INT,
    CONSTRAINT FK_ID_PESSOA_EMPREGADO FOREIGN KEY (ID_PESSOA) REFERENCES PESSOAS(ID_PESSOA),
    CONSTRAINT FK_ID_CARGO FOREIGN KEY (ID_CARGO) REFERENCES CARGO(ID_CARGO)
);

CREATE TABLE IF NOT EXISTS CARGO (
    ID_CARGO INT PRIMARY KEY,
    NOME_CARGO VARCHAR(150) NOT NULL,
    CARGA_HORARIA_CARGO TIME NOT NULL
);

CREATE TABLE IF NOT EXISTS QUALIFICACOES (
    ID_EMPREGADO INT PRIMARY KEY,
    QUALIFICACOES TEXT NOT NULL,
    TEMPO_NA_AREA INT NOT NULL,
    CONSTRAINT FK_ID_EMPREGADO_QUALIFICACAO FOREIGN KEY (ID_EMPREGADO) REFERENCES EMPREGADOS(ID_EMPREGADO)
);

CREATE TABLE IF NOT EXISTS EMPRESAS (
    CNPJ_EMPRESA INT PRIMARY KEY,
    RAZAO_SOCIAL VARCHAR(90) NOT NULL,
    PESSOA_CONTATO TEXT NOT NULL,
    EMAIL_EMPRESA VARCHAR(90) NOT NULL,
    ID_ENDERECO INT,
    CONSTRAINT FK_ID_ENDERECO_EMPRESAS FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECOS(ID_ENDERECO)
);

CREATE TABLE IF NOT EXISTS FORNECEDORES (
    CNPJ_FORNECEDOR INT PRIMARY KEY,
    RAZAO_SOCIAL VARCHAR(90) NOT NULL,
    PESSOA_CONTATO TEXT NOT NULL,
    EMAIL_FORNEC VARCHAR(90) NOT NULL,
    ID_ENDERECO INT,
    CONSTRAINT FK_ID_ENDERECO_FORNECE FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECOS(ID_ENDERECO)
);

CREATE TABLE IF NOT EXISTS TELEFONES (
    ID_TELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    NUMERO VARCHAR(14),
    ID_PESSOA INT,
    CONSTRAINT FK_ID_PESSOA_TELEFONE FOREIGN KEY (ID_PESSOA) REFERENCES PESSOAS(ID_PESSOA)
);

CREATE TABLE IF NOT EXISTS TIPO_COMPONENTE (
    ID_TIPO_COMPONENTE INT PRIMARY KEY,
    DESCRICAO VARCHAR(45) NOT NULL,
    MATERIAL VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS COMPONENTES (
    ID_COMPONENTE INT PRIMARY KEY,
    NOME_COMPONENTE VARCHAR(100),
    QUANTIDADE_ESTOQUE DECIMAL NOT NULL,
    PRECO_UNITARIO DECIMAL NOT NULL,
    DATA_ULT_ATUALIZACAO DATE,
    ID_TIPO_COMPONENTE INT,
    CONSTRAINT FK_ID_TIPO_COMPONENTE FOREIGN KEY (ID_TIPO_COMPONENTE) REFERENCES TIPO_COMPONENTE(ID_TIPO_COMPONENTE)
);

CREATE TABLE IF NOT EXISTS PRODUTOS (
    ID_PROD INT PRIMARY KEY,
    NOME_PROD VARCHAR(45) NOT NULL,
    DIMENS_PROD VARCHAR(45) NOT NULL,
    PESO_PROD DECIMAL(10,2) NOT NULL,
    PRECO_PROD DECIMAL NOT NULL,
    TEMPO_FABRICACAO TIME NOT NULL,
    DESENHO_PROD VARCHAR(100) NOT NULL,
    HRMAODEOBRA_PROD TIME NOT NULL,
    CATEGORIA_PROD VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS RECURSOS_ESPECIFICOS (
    ID_RE INT PRIMARY KEY,
    QUANT_NECESS_RE INT,
    TEMPOUSO_RE TIME NOT NULL,
    TEMPO_MAO_DE_OBRA_RE TIME NOT NULL,
    CUSTO_RE DECIMAL(10,2),
    ID_PROD INT,
    ID_COMPONENTE INT,
    CONSTRAINT FK_ID_PRODU FOREIGN KEY (ID_PROD) REFERENCES PRODUTOS(ID_PROD),
    CONSTRAINT FK_ID_COMPONENTERE FOREIGN KEY (ID_COMPONENTE) REFERENCES COMPONENTES(ID_COMPONENTE)
);

CREATE TABLE IF NOT EXISTS ENCOMENDAS (
    ID_ENCOM INT PRIMARY KEY,
    DATA_INCLUSAO DATE NOT NULL,
    VALORTOTAL_ENCOM DECIMAL(10,2) NOT NULL,
    VALORLIQUI_ENCOM DECIMAL(10,2) NOT NULL,
    ID_CLIENTE INT,
    CONSTRAINT FK_ID_CLIENTEE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE IF NOT EXISTS ENCOMENDAS_PRODUTOS (
    ID_ENCOM INT,
    ID_PROD INT,
    QUANTIDADE INT,
    PRIMARY KEY (ID_ENCOM, ID_PROD),
    CONSTRAINT FK_ID_ENCOMEP FOREIGN KEY (ID_ENCOM) REFERENCES ENCOMENDAS(ID_ENCOM),
    CONSTRAINT FK_ID_PRODEP FOREIGN KEY (ID_PROD) REFERENCES PRODUTOS(ID_PROD)
);

CREATE TABLE IF NOT EXISTS FORMA_DE_PAGAMENTO (
    CODIGO_PAGAMENTO INT PRIMARY KEY,
    ID_ENCOM INT NOT NULL,
    ID_PROD INT NOT NULL,
    TIPO_PAGAMENTO VARCHAR(50),
    CONSTRAINT FK_ID_ENCOM FOREIGN KEY (ID_ENCOM) REFERENCES ENCOMENDAS(ID_ENCOM),
    CONSTRAINT FK_ID_PROD FOREIGN KEY (ID_PROD) REFERENCES PRODUTOS(ID_PROD)
);

CREATE TABLE IF NOT EXISTS FORNECEDORES_COMPONENTES (
    CNPJ_FORNECEDOR INT,
    ID_COMPONENTE INT,
    PRECO_COMPRA DECIMAL(10,2),
    PRIMARY KEY (CNPJ_FORNECEDOR, ID_COMPONENTE),
    CONSTRAINT FK_CNPJ_FORNECEDOR FOREIGN KEY (CNPJ_FORNECEDOR) REFERENCES (FORNECEDORES)
);

ALTER TABLE CLIENTES
    ADD COLUMN EMAIL_CLIENTE VARCHAR(100),
    DROP COLUMN RAMOATVDD_CLIENTE,
    MODIFY COLUMN RZSOCIAL_CLIENTE VARCHAR(200),
    CHANGE COLUMN DATACADST_CLIENTE DATA_CADASTRAMENTO_CLIENTE DATE NOT NULL;

ALTER TABLE EMPREGADOS
    ADD COLUMN RESUMO_PROFISSIONAL_EMPREGADO TEXT(100),
    ADD COLUMN EMAIL_EMPREGADO VARCHAR(100),
    MODIFY COLUMN DATAADM_EMPREGADO DATETIME NOT NULL,
    CHANGE COLUMN NOME_EMPREGADO NOME_CP_EMPREGADO VARCHAR(100);

ALTER TABLE TELEFONE_EMPREGADOS
    ADD COLUMN DDD_REGIAO_EMPREGADO VARCHAR(3),
    ADD COLUMN UF_REGIAO_EMPREGADO VARCHAR(2),
    MODIFY COLUMN TELEFONES VARCHAR(14),
    RENAME COLUMN TELEFONES TO CELULAR;

ALTER TABLE CARGO
    ADD COLUMN CARGA_HORARIA_CARGO TIME NOT NULL,
    DROP COLUMN SALARIO_CARGO,
    MODIFY COLUMN NOME_CARGO VARCHAR(150),
    RENAME COLUMN NOME_CARGO TO CARGO_NOME;

ALTER TABLE QUALIFICACOES
    ADD COLUMN CERTIFICACOES TEXT(100),
    ADD COLUMN RESUMO_PROFISSIONAL TEXT (100),
    MODIFY COLUMN QUALIFICACAO_EMPREGADO TEXT NOT NULL,
    RENAME COLUMN QUALIFICACAO_EMPREGADO TO QUALIFICACOES_EMPREGADO;

ALTER TABLE EMPRESAS
    ADD COLUMN EMAIL_EMPRESA VARCHAR(100),
    DROP COLUMN RZSOZIAL_EMPRESA,
    MODIFY COLUMN EMAIL_EMPRESA VARCHAR(90) NOT NULL,
    CHANGE COLUMN RZSOZIAL_EMPRESA RAZAOSC_EMPRESA VARCHAR(90);

ALTER TABLE TELEFONE_EMPRESAS
    ADD COLUMN DDD_REGIAO VARCHAR(3),
    ADD COLUMN UF_REGIAO VARCHAR(2),
    MODIFY COLUMN TELEFONES VARCHAR(14),
    RENAME COLUMN TELEFONES TO CELULAR;

ALTER TABLE FORNECEDORES
    ADD COLUMN EMAIL_FORNEC VARCHAR(100) NOT NULL,
    DROP COLUMN PCONTATO_FORNEC,
    MODIFY COLUMN EMAIL_FORNEC VARCHAR(90) NOT NULL,
    CHANGE COLUMN RZSOZIAL_FORNECE RAZAOSC_FORNECE VARCHAR(90);

ALTER TABLE TELEFONE_FORNECEDORES
    ADD COLUMN LOCALIDADE_FORNECEDOR VARCHAR(100),
    ADD COLUMN DDD/UF VARCHAR(6),
    MODIFY COLUMN TELEFONES VARCHAR(14),
    RENAME COLUMN TELEFONES TO CELULAR;

ALTER TABLE TIPO_DE_ENDERECO
    ADD COLUMN LOCALIDADE_ENDERECO VARCHAR(100),
    ADD COLUMN USO_PRINCIPAL VARCHAR(50),
    MODIFY COLUMN NOME VARCHAR(200),
    RENAME COLUMN NOME TO DESCRICAO;

ALTER TABLE ENDERECOS
    ADD COLUMN END_OBSERVACOES TEXT,
    DROP COLUMN END_NUMRUA,
    MODIFY COLUMN END_CEP CHAR(8) NOT NULL,
    CHANGE COLUMN END_LOGRADOURO END_TIPO_LOGRADOURO VARCHAR(100) NOT NULL;

ALTER TABLE PRODUTOS
    ADD COLUMN CATEGORIA_PROD VARCHAR(50),
    DROP COLUMN COR_PROD,
    MODIFY COLUMN PESO_PROD DECIMAL(10,2),
    CHANGE COLUMN TEMPFABRI_PROD TEMPO_FABRICACAO TIME NOT NULL;

ALTER TABLE RECURSOS_ESPECIFICOS
    ADD COLUMN CUSTO_RE DECIMAL(10,2),
    DROP COLUMN UNIDADE_RE,
    MODIFY COLUMN QUANT_NECESS_RE INT,
    CHANGE COLUMN HR_MAO_DE_OBRA_RE TEMPO_MAO_DE_OBRA TIME NOT NULL;

ALTER TABLE ENCOMENDAS
    ADD COLUMN ID_CLIENTE INT,
    DROP COLUMN VALORDESCO_ENCOM,
    MODIFY COLUMN VALORTOTAL_ENCOM DECIMAL(10,2) NOT NULL,
    MODIFY COLUMN VALORLIQUI_ENCOM DECIMAL(10,2) NOT NULL,
    CHANGE COLUMN DATINCLUS_ENCOM DATA_INCLUSAO DATE NOT NULL;

ALTER TABLE FORMA_DE_PAGAMENTO
    ADD COLUMN TIPO_PAGAMENTO VARCHAR(50),
    MODIFY COLUMN ID_ENCOM INT NOT NULL,
    MODIFY COLUMN ID_PROD INT NOT NULL,
    CHANGE COLUMN ID_FORMA_PAGAMENTO CODIGO_PAGAMENTO INT PRIMARY KEY;

ALTER TABLE ENCOMENDAS_PRODUTOS
    ADD COLUMN QUANTIDADE INT,
    ADD COLUMN HORARIO_DE_COMPRA DATA TIME,
    DROP PRIMARY KEY,
    DROP COLUMN ID_ENCOM;

ALTER TABLE TIPO_COMPONENTE
    ADD COLUMN MATERIAL VARCHAR(50),
    MODIFY COLUMN NOME_TIPO_COMPONENTE VARCHAR(100) NOT NULL,
    MODIFY COLUMN ID_TIPO_COMPONENTE INT UNIQUE NOT NULL,
    RENAME COLUMN NOME_TIPO_COMPONENTE TO DESCRICAO;


ALTER TABLE COMPONENTES
    ADD COLUMN DATA_ULT_ATUALIZACAO DATE,
    DROP COLUMN UNIDADE_COMPONENTE,
    MODIFY COLUMN NOME_COMPONENTE VARCHAR(100),
    CHANGE COLUMN QUANTESTOQUE_COMPONENTE QUANTIDADE_ESTOQUE DECIMAL NOT NULL;

ALTER TABLE FORNECEDORES_COMPONENTES
    ADD COLUMN PRECO_COMPRA DECIMAL(10,2),
    MODIFY COLUMN CNPJ_FORNEC VARCHAR(20)
    RENAME COLUMN CNPJ_FORNEC TO CNPJ_FORNECEDOR,
    DROP PRIMARY KEY;

ALTER TABLE MAQUINAS
    ADD COLUMN NUMERO_SERIE VARCHAR(50),
    DROP COLUMN TEMPOVIDA_MAQUINA,
    MODIFY COLUMN DATACOMPRA_MAQUINA DATE NOT NULL,
    MODIFY COLUMN DTFIMGARANTIA_MAQUINA DATE NOT NULL,
    CHANGE COLUMN TEMPOVIDA_MAQUINA TEMPO_VIDA_ESTIMADO DATETIME NOT NULL;

ALTER TABLE REGISTRO_MANUTENCAO
    ADD COLUMN CUSTO_MANUTENCAO DECIMAL(10,2),
    DROP COLUMN DESCRICAO_RM,
    MODIFY COLUMN DATA_RM DATETIME NOT NULL,
    CHANGE COLUMN ID_RM CODIGO_MANUTENCAO INT PRIMARY KEY;

DROP DATABASE ERP_EMPRESARIAL;