#Criando o banco de dados
CREATE SCHEMA IF NOT EXISTS ACADEMIA_SAUDE_EM_MOVIMENTO; 
USE ACADEMIA_SAUDE_EM_MOVIMENTO; 

#Criando tabela para armazenar alunos 
CREATE TABLE IF NOT EXISTS ALUNOS(
ID_ALUNO INT AUTO_INCREMENT PRIMARY KEY,
ALUNO_NOME VARCHAR(100) NOT NULL,
ALUNO_CPF VARCHAR(11) NOT NULL UNIQUE, 
ALUNO_DATA_NASC DATE NOT NULL, 
ID_ENDERECO INT, CONSTRAINT 
FK_ID_ENDERECO_ALUNO FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECOS(ID_ENDERECO) 
);

#Criando tabela para armazenar endereços 
CREATE TABLE IF NOT EXISTS ENDERECOS( 
  ID_ENDERECO INT AUTO_INCREMENT PRIMARY KEY, 
  RUA VARCHAR(100) NOT NULL, 
  NUMERO INT, BAIRRO VARCHAR(100) NOT NULL, 
  CIDADE VARCHAR(100) NOT NULL, 
  ESTADO VARCHAR(2) NOT NULL, 
  CEP VARCHAR(14) NOT NULL 
); 

#Criando tabela para armazenar modalidades 
CREATE TABLE IF NOT EXISTS MODALIDADES( 
  ID_MODALIDADE INT AUTO_INCREMENT PRIMARY KEY, 
  NOME VARCHAR(100) NOT NULL, 
  DESCRICAO TEXT 
);

#Criando tabela para armazenar instrutores 
CREATE TABLE IF NOT EXISTS INSTRUTORES(
  ID_INSTRUTOR INT AUTO_INCREMENT PRIMARY KEY, 
  NOME VARCHAR(100) NOT NULL, 
  ESPECIALIDADE VARCHAR(100) NOT NULL,
  ID_MODALIDADE INT, 
  CONSTRAINT FK_ID_MODALIDADE_INSTRUTOR FOREIGN KEY (ID_MODALIDADE) REFERENCES MODALIDADES(ID_MODALIDADE) 
);
  
#Criando tabela para armazenar planos de treinamento 
CREATE TABLE IF NOT EXISTS PLANO_DE_TREINAMENTO( 
ID_PT INT AUTO_INCREMENT PRIMARY KEY,
DATA_INICIO DATE NOT NULL, 
OBJETIVO TEXT NOT NULL, 
ID_ALUNO INT, 
ID_INSTRUTOR INT, 
CONSTRAINT FK_ID_ALUNO_PT FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS(ID_ALUNO),
CONSTRAINT FK_ID_INSTRUTOR_PT FOREIGN KEY (ID_INSTRUTOR) REFERENCES INSTRUTORES(ID_INSTRUTOR) 
);

#Criando tabela para armazenar aulas 
CREATE TABLE IF NOT EXISTS AULAS(
ID_AULA INT AUTO_INCREMENT PRIMARY KEY,
DATA_HORA DATETIME NOT NULL,
CAPACIDADE INT NOT NULL,
ID_MODALIDADE INT,
ID_INSTRUTOR INT, CONSTRAINT FK_ID_MODALIDADE_AULA FOREIGN KEY (ID_MODALIDADE) REFERENCES MODALIDADES(ID_MODALIDADE),
CONSTRAINT FK_ID_INSTRUTOR_AULA FOREIGN KEY (ID_INSTRUTOR) REFERENCES INSTRUTORES(ID_INSTRUTOR) 
);

#Criando tabela para armazenar pagamentos 
CREATE TABLE IF NOT EXISTS PAGAMENTOS(
ID_PAGA INT AUTO_INCREMENT PRIMARY KEY,
VALOR DECIMAL(10, 2) NOT NULL,
CRONOGRAMA_PAGAMENTO DATA TIME NOT NULL,
ID_ALUNO INT, CONSTRAINT FK_ID_ALUNO_PAGA FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS(ID_ALUNO) 
);

#Criando tabela associativa entre alunos e modalidades 
CREATE TABLE IF NOT EXISTS ALUNOS_MODALIDADES(
ID_ALUNO INT,
ID_MODALIDADE INT,
PRIMARY KEY (ID_ALUNO, ID_MODALIDADE),
CONSTRAINT FK_ID_ALUNO_AM FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS(ID_ALUNO),
CONSTRAINT FK_ID_MODALIDADE_AM FOREIGN
);

ALTER TABLE ALUNOS ADD EMAIL VARCHAR (100);
ALTER TABLE ALUNOS DROP COLUMN ALUNO_NUMRUA INT;
ALTER TABLE ALUNOS MODIFY COLUMN ALUNO_CEP VARCHAR (9);
ALTER TABLE ALUNOS CHANGE COLUMN ALUNO_NOME ALUNO_NOMECOMPLETO VARCHAR (100);


ALTER TABLE MODALIDADES
ADD COLUMN MODALIDADE_NIVEL ENUM('INICIANTE','INTERMEDIARIO','AVANCADO');
ALTER TABLE MODALIDADES DROP COLUMN MODALIDADE_DESCRICAO;
ALTER TABLE MODALIDADES MODIFY COLUMN MODALIDADE_NOME VARCHAR (200) NOT NULL;
ALTER TABLE MODALIDADES 
CHANGE COLUMN MODALIDADE_NOME NOME_MODALIDADE VARCHAR (200) NOT NULL;


ALTER TABLE INSTRUTORES ADD INSTRUTOR_TELEFONE VARCHAR(20);
ALTER TABLE INSTRUTORES DROP COLUMN INSTRUTOR_ESPEC;
ALTER TABLE INSTRUTORES
MODIFY COLUMN INSTRUTOR_NOME VARCHAR(150) NOT NULL;
ALTER TABLE INSTRUTORES
CHANGE COLUMN INSTRUTOR_NOME NOME_INSTRUTOR VARCHAR(150) NOT NULL;


ALTER TABLE PLANO_DE_TREINAMENTO ADD COLUMN PT_DURACAO INT;
ALTER TABLE PLANO_DE_TREINAMENTO DROP COLUMN PT_OBJETIVO;
ALTER TABLE PLANO_DE_TREINAMENTO
MODIFY COLUMN PT_DATA_INICIO DATE DEFAULT CURRENT_DATE;
ALTER TABLE PLANO_DE_TREINAMENTO
CHANGE COLUMN PT_DATA_INICIO PT_DATA_INICIO_TREINO DATE NOT NULL;


ALTER TABLE AULAS ADD COLUMN AULA_OBSERVACOES TEXT;
ALTER TABLE AULAS DROP COLUMN AULA_CAPACIDADE;
ALTER TABLE AULAS 
CHANGE COLUMN AULA_DATA_HORA AULA_HORARIO DATETIME NOT NULL;
ALTER TABLE AULAS MODIFY COLUMN AULA_DATA_HORA TIME NOT NULL;


ALTER TABLE PAGAMENTOS
ADD COLUMN PAGA_FORMA_PAGTO ENUM('DINHEIRO', 'CARTAO', 'CHEQUE');
ALTER TABLE PAGAMENTOS DROP COLUMN PAGA_DATA;
ALTER TABLE PAGAMENTOS
MODIFY COLUMN PAGA_VALOR DECIMAL(12,2) NOT NULL;
ALTER TABLE PAGAMENTOS
CHANGE COLUMN PAGA_VALOR VALOR_PAGA DECIMAL(12,2) NOT NULL;


DROP TABLE ACADEMIA_SAUDE_EM_MOVIMENTO;